### ISSUE TITLE
Dubious semantics on "cheaile"

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/j-sheridan-le-fanu_uncle-silas#2]
While looking into an unrelated issue, I noticed these "z3398:place" semantics in [chapter-2-27](https://github.com/standardebooks/j-sheridan-le-fanu_uncle-silas/blob/4cde904a505a574b462f41f8bb02807a2327464f/src/epub/text/chapter-2-27.xhtml):

`				<p>“Do you mean to say, Madame, that you really think those chisellings and screws are forty years old?”</p>
				<p>“How can I tell, **<span epub:type="z3998:place">cheaile</span>**? What does signify whether it is forty or only fourteen years? Bah! we ’av other theeng to theenk about. Those villain men! I am glad to see bar and bolt, and lock and key, at least, to our room, to keep soche faylows out!”</p>`

This looks like a straightforward dialect spelling of "child" to me, not a place. I think the semantics are incorrect and can just be removed.

The word "cheaile" appears a couple times in the same chapter. Some have this place semantic and others have no semantics at all. I haven't checked the rest of the book.

I can come back to this later and do a more thorough investigation if no one gets to it first.

**Comment by acabal** [comment]
Yes, looks like an error. Can you open a PR?

**Comment by tuskpot** [comment]
Yes, no problem. I'll look over the rest of the book and submit a PR today or tomorrow.
